#!/bin/bash

COMMANDS=(zsh stow git curl unzip fzf fd exa)

check_cmd() {
  command -v "$1" > /dev/null 2>&1
}

main() {
  for cmd in "${COMMANDS[@]}"; do
      if ! check_cmd $cmd; then
        printf 'check failed, command `%s` not found.\n' $cmd
      fi
  done
}

main
